agent:
  name: "alemetric-agent"
  pollInterval: 2
  reportInterval: 10
  host: "127.0.0.1"
  port: "8080"

server:
  name: "alemetric-server"
  host: "127.0.0.1"
  port: "8080"

logger:
  level: "debug"