agent:
  name: alemetric-agent
  pollInterval: 2
  reportInterval: 10
  host: 127.0.0.1
  port: 8080
  metricsNames:
    - Alloc
    - BuckHashSys
    - Frees
    - GCCPUFraction
    - GCSys
    - HeapAlloc
    - HeapIdle
    - HeapInuse
    - HeapObjects
    - HeapReleased
    - HeapSys
    - LastGC
    - Lookups
    - MCacheInuse
    - MCacheSys
    - MSpanInuse
    - MSpanSys
    - Mallocs
    - NextGC
    - NumForcedGC
    - NumGC
    - OtherSys
    - PauseTotalNs
    - StackInuse
    - StackSys
    - Sys
    - TotalAlloc
    - RandomValue
    - PollCount

server:
  name: alemetric-server
  host: 127.0.0.1
  port: 8080

logger:
  level: debug