agent:
  name: alemetric-agent
  pollInterval: 2s
  reportInterval: 10s
  serverURL: "127.0.0.1:8080"
  metricsNames:
    - Alloc
    - BuckHashSys
    - Frees
    - GCCPUFraction
    - GCSys
    - HeapAlloc
    - HeapIdle
    - HeapInuse
    - HeapObjects
    - HeapReleased
    - HeapSys
    - LastGC
    - Lookups
    - MCacheInuse
    - MCacheSys
    - MSpanInuse
    - MSpanSys
    - Mallocs
    - NextGC
    - NumForcedGC
    - NumGC
    - OtherSys
    - PauseTotalNs
    - StackInuse
    - StackSys
    - Sys
    - TotalAlloc
    - RandomValue
    - PollCount

server:
  name: alemetric-server
  address: "127.0.0.1:8080"
  storeInternal: 0s
  storeFile: "/tmp/devops-metrics-db.json"
  restore: false

logger:
  level: debug